name: fleetbase/leaflet-routing-machine

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }} & Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Enable Corepack & activate Yarn 3.6.4
        run: |
          corepack enable
          corepack prepare yarn@3.6.4 --activate
  
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn bundle

  npm_publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18.x & Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Enable Corepack & activate Yarn 3.6.4
        run: |
          corepack enable
          corepack prepare yarn@3.6.4 --activate
  
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn bundle

      - name: Set up npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish --access public

  github_publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18.x & Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Enable Corepack & activate Yarn 3.6.4
        run: |
          corepack enable
          corepack prepare yarn@3.6.4 --activate

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn bundle

      - name: Configure GitHub registry
        run: |
          echo "@fleetbase:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish